const icon=(name)=>({menu:'<svg viewBox="0 0 24 24"><path d="M4 8h16M4 16h16"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></svg>',bag:'<svg viewBox="0 0 24 24"><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></svg>',close:'<svg viewBox="0 0 24 24"><path d="m5 5 14 14M19 5 5 19"/></svg>',arrow:'<svg viewBox="0 0 24 24"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>'}[name]);
function shell(){
 const header=`<a class="skip-link" href="#main">Skip to content</a><div class="announcement">Complimentary shipping on originals across India</div><header class="site-header"><a class="brand" href="index.html" aria-label="Shalini Mall home"><span>Shalini Mall</span></a><nav class="desktop-nav" aria-label="Primary"><a href="shop.html">Shop</a><a href="originals.html">Originals</a><a href="prints.html">Prints</a><a href="about.html">About</a><a href="contact.html">Contact</a></nav><div class="header-actions"><button class="icon-btn" data-open="search" aria-label="Search">${icon('search')}</button><button class="icon-btn cart-button" data-open="cart" aria-label="Open cart">${icon('bag')}<span data-cart-count>0</span></button><button class="icon-btn menu-btn" data-open="menu" aria-label="Open menu">${icon('menu')}</button></div></header>`;
 const panels=`<div class="scrim" data-close></div><aside class="panel menu-panel" id="menuPanel" aria-hidden="true"><div class="panel-head"><span class="brand mini"><span>Shalini Mall</span></span><button class="icon-btn" data-close aria-label="Close menu">${icon('close')}</button></div><nav><a href="index.html">Home</a><a href="shop.html">Shop all</a><a href="originals.html">Originals</a><a href="prints.html">Fine art prints</a><a href="about.html">The artist</a><a href="contact.html">Contact</a></nav><div class="panel-foot"><a href="https://www.instagram.com/" rel="noopener">Instagram</a><a href="https://www.pinterest.com/" rel="noopener">Pinterest</a></div></aside><aside class="panel cart-panel" id="cartPanel" aria-hidden="true"><div class="panel-head"><h2>Your collection</h2><button class="icon-btn" data-close aria-label="Close cart">${icon('close')}</button></div><div id="cartItems" class="cart-items"></div><div class="cart-summary"><div><span>Subtotal</span><strong id="cartSubtotal">₹0</strong></div><p>Shipping and taxes calculated at checkout.</p><a class="button dark full" href="cart.html">Review cart</a></div></aside><section class="search-overlay" id="searchPanel" aria-hidden="true"><div class="search-top"><label for="searchInput">Search the collection</label><button class="icon-btn" data-close aria-label="Close search">${icon('close')}</button></div><input id="searchInput" type="search" placeholder="Try “print” or “Monsoon”" autocomplete="off"><div id="searchResults" class="search-results"></div></section>`;
 const footer=`<section class="newsletter"><p class="eyebrow">Notes from the studio</p><h2>Art, process, and new work—occasionally.</h2><form id="newsletterForm" novalidate><label class="sr-only" for="newsletterEmail">Email address</label><input id="newsletterEmail" type="email" placeholder="Email address" required><button type="submit">Subscribe ${icon('arrow')}</button><small class="form-message" aria-live="polite"></small></form></section><footer><a class="brand inverse" href="index.html"><span>Shalini Mall</span></a><div class="footer-links"><div><b>Collect</b><a href="originals.html">Originals</a><a href="prints.html">Prints</a><a href="shop.html">All artwork</a></div><div><b>Studio</b><a href="about.html">About</a><a href="contact.html">Contact</a><a href="contact.html#faq">FAQ</a></div><div><b>Follow</b><a href="https://www.instagram.com/" rel="noopener">Instagram</a><a href="https://www.pinterest.com/" rel="noopener">Pinterest</a><a href="https://www.facebook.com/" rel="noopener">Facebook</a></div></div><div class="legal"><span>© 2026 Shalini Mall Studio</span><span>Privacy · Terms · Shipping</span></div></footer><div class="toast" role="status" aria-live="polite"></div>`;
 document.body.insertAdjacentHTML('afterbegin',header+panels);document.body.insertAdjacentHTML('beforeend',footer);
}
function productCard(p){return `<article class="product-card" data-category="${p.category}" data-price="${p.price}" data-title="${p.title}"><a class="product-image" href="product.html?id=${p.id}" style="--crop:${p.crop}"><img src="assets/images/collection-hero.png" alt="Detail of ${p.title}" loading="lazy"><span>${p.status}</span></a><div class="product-meta"><div><h3><a href="product.html?id=${p.id}">${p.title}</a></h3><p>${p.category} · ${p.size}</p></div><strong>${money(p.price)}</strong></div></article>`}
function openPanel(type){closePanels();document.body.classList.add('locked','overlay-open');const el=document.querySelector(`#${type}Panel`);el.classList.add('open');el.setAttribute('aria-hidden','false');setTimeout(()=>el.querySelector('button,input,a')?.focus(),50)}
function closePanels(){document.body.classList.remove('locked','overlay-open');document.querySelectorAll('.panel,.search-overlay').forEach(x=>{x.classList.remove('open');x.setAttribute('aria-hidden','true')})}
function showToast(msg){const t=document.querySelector('.toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
document.addEventListener('DOMContentLoaded',()=>{
 shell();renderCart();
 document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open)openPanel(open.dataset.open);if(e.target.closest('[data-close]'))closePanels()});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanels()});
 const input=document.querySelector('#searchInput');input.addEventListener('input',()=>{const q=input.value.toLowerCase().trim();document.querySelector('#searchResults').innerHTML=q?ART_PRODUCTS.filter(p=>(p.title+p.category).toLowerCase().includes(q)).map(p=>`<a href="product.html?id=${p.id}"><span>${p.title}<small>${p.category}</small></span><b>${money(p.price)}</b></a>`).join('')||'<p>No artworks found.</p>':''});
 document.querySelector('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();const email=e.currentTarget.querySelector('input'),msg=e.currentTarget.querySelector('.form-message');if(!email.validity.valid){msg.textContent='Please enter a valid email address.';email.focus();return}msg.textContent='Welcome to the studio. Thank you.';e.currentTarget.reset()});
 const header=document.querySelector('.site-header');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30),{passive:true});
});
window.productCard=productCard;window.openPanel=openPanel;window.showToast=showToast;
